name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "yuukibaby.top"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "yuukibaby.top"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "dockernew.yuukibaby.top", custom_domain = true },
  { pattern = "quay.yuukibaby.top", custom_domain = true },
  { pattern = "gcr.yuukibaby.top", custom_domain = true },
  { pattern = "k8s-gcr.yuukibaby.top", custom_domain = true },
  { pattern = "k8s.yuukibaby.top", custom_domain = true },
  { pattern = "ghcr.yuukibaby.top", custom_domain = true },
  { pattern = "cloudsmith.yuukibaby.top", custom_domain = true },
  { pattern = "docker-staging.yuukibaby.top", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
route = { pattern = "docker-staging.yuukibaby.top", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
